/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_wasmclient_free: (a: number, b: number) => void;
export const __wbg_rpchandle_free: (a: number, b: number) => void;
export const rpchandle_cancel: (a: number) => void;
export const wasmclient_open: (a: number, b: number) => any;
export const wasmclient_join_federation: (a: number, b: number, c: number, d: number) => any;
export const wasmclient_parse_invite_code: (a: number, b: number) => [number, number, number, number];
export const wasmclient_parse_bolt11_invoice: (a: number, b: number) => [number, number, number, number];
export const wasmclient_preview_federation: (a: number, b: number) => any;
export const wasmclient_rpc: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: any) => number;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const intounderlyingbytesource_type: (a: number) => [number, number];
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_start: (a: number, b: any) => void;
export const intounderlyingbytesource_pull: (a: number, b: any) => any;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingsource_pull: (a: number, b: any) => any;
export const intounderlyingsource_cancel: (a: number) => void;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const intounderlyingsink_write: (a: number, b: any) => any;
export const intounderlyingsink_close: (a: number) => any;
export const intounderlyingsink_abort: (a: number, b: any) => any;
export const ring_core_0_17_14__bn_mul_mont: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const rustsecp256k1_v0_10_0_context_create: (a: number) => number;
export const rustsecp256k1_v0_10_0_context_destroy: (a: number) => void;
export const rustsecp256k1_v0_10_0_default_illegal_callback_fn: (a: number, b: number) => void;
export const rustsecp256k1_v0_10_0_default_error_callback_fn: (a: number, b: number) => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export_5: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const closure2_externref_shim: (a: number, b: number, c: any) => void;
export const closure6244_externref_shim: (a: number, b: number, c: any) => void;
export const _dyn_core__ops__function__Fn_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hd3bf70b599f3547d: (a: number, b: number) => void;
export const _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__he3cc3f4965d04a65: (a: number, b: number) => void;
export const closure7684_externref_shim: (a: number, b: number, c: any) => void;
export const _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h350d4791d89dc5e2: (a: number, b: number) => void;
export const closure7708_externref_shim: (a: number, b: number, c: any) => void;
export const _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h56bfa92294ddbd06: (a: number, b: number) => void;
export const closure8297_externref_shim: (a: number, b: number, c: any) => void;
export const _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hfd9c6b0ff54c4e4f: (a: number, b: number) => void;
export const closure8647_externref_shim: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_start: () => void;
